### ISSUE TITLE
Dont fetch fonts from fonts.google.com

### ISSUE THREAD

**Issue by ammarbinfaisal** [ammarbinfaisal/cms-aliganj-mun#7]
save them and use font-face. they also take 150ms on an average

**Comment by ammarbinfaisal** [comment]
@gaurangtandon is this really a problem? (their taking 150ms for loading)

**Comment by GaurangTandon** [comment]
Have a look at https://stackoverflow.com/questions/29091014/how-do-i-leverage-browser-caching-for-google-fonts

In general, 

> As the Google Fonts API becomes more widely used, it is likely visitors to your site or page will already have any Google fonts used in your design in their browser cache.

from the [Google FAQ of their fonts](https://developers.google.com/fonts/faq#will_web_fonts_slow_down_my_page).

So, it is better not to host them on your own server.

**Comment by ammarbinfaisal** [comment]
thank you, this was the first time I used lighthouse(for this website) and it said that this and fontawesom are ccritical request chains(or something like that , I dont remember the exact text) therefore I opened this issue
